### ISSUE TITLE
product update duplicates entry

### ISSUE THREAD

**Issue by domssilva** [Furniture-Shop/server#13]
[ProductController.update](https://github.com/Furniture-Shop/server/blob/63509002d6437ef2f855784a63acd5934adbe5fd/controllers/product.js#L78) is not working as expected. Instead of updating the current product, it's creating a new one. 

## Steps to reproduce the bug
1. Create a product
2. Make a PUT request to edit this product `/api/product/:pid`
3. Go to /api/product to check all products

Now you will see that instead of having 1 updated product we will have the old product + a new one

**Comment by PrimphByter** [comment]
Thanks. I fixed it
