### ISSUE TITLE
Error handling is not working properly

### ISSUE THREAD

**Issue by PrimphByter** [Furniture-Shop/server#27]
When an error occurs, whether it's the db fault or the request fault, the error handling always returns `[Object, object]` as a message with the 500 error code

**Comment by ceoshikhar** [comment]
Is this project back in progress?

**Comment by PrimphByter** [comment]
You probably weren't online when Ricky talked about that. You can try to talk with him

**Comment by PrimphByter** [comment]
This was resolved when I switched back to the main branch (development)
